dist: trusty
sudo: false
language: cpp


notifications:
  email:
    on_success: never
    on_failure: always


compiler:
  - g++
  - clang++


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8
      - g++-7
      - libboost-dev


install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"


before_script:
- cd src


script:
- make vita
