dist: bionic
language: cpp
sudo: false

notifications:
  email:
    on_success: never
    on_failure: always


compiler:
  - g++
  - clang++


before_script:
- mkdir -p build
- cd build/
- cmake ../src


script:
- make
