dist: trusty
sudo: false

language: cpp

compiler:
  - g++
  - clang++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8
      - g++-6
      - libboost-dev

install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

script: cd src; make vita