dist: trusty
language: cpp
sudo: false


notifications:
  email:
    on_success: never
    on_failure: always


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"


before_install:
  - eval "${MATRIX_EVAL}"


before_script:
- cd src


script:
- make vita
