dist: bionic
language: cpp


notifications:
  email:
    on_success: never
    on_failure: always


compiler:
  - g++
  - clang++


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-8
    packages:
      - clang-8
      - g++-9
      - libstdc++-8-dev

install:
- "[ $CXX = g++ ] && export CXX=g++-9 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-8.0 || true"


before_script:
- mkdir -p build
- cd build/
- cmake ../src


script:
- make
