dist: trusty
sudo: false
language: cpp


notifications:
  email:
    on_success: never
    on_failure: always


compiler:
  - g++
  - clang++


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - g++-7


install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-5.0 || true"


before_script:
- cd src
- mkdir -p build
- cd build/
- cmake ..


script:
- make
