dist: trusty
language: cpp
sudo: required


notifications:
  email:
    on_success: never
    on_failure: always


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libc++-dev
            - libc++abi-dev
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"


before_install:
  - eval "${MATRIX_EVAL}"


before_script:
- cd src


script:
- make vita
