language: cpp

compiler:
  - g++
#  - clang++

os: linux

cache:
  apt: true

packages:
  - gcc-4.9
  - g++-4.9
  - libboost1.55-all-dev

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev

script: make tests